swagger: "2.0"

info:
  title: "Variation Modelling Collaboration"
  description: |
    Standardized exchange of biological sequence variation
    This file may be referenced directly in clients and servers as
    (URL TBD)
  version: "0.0"
  contact:
    name: "Variation Modelling Collaboration"
    url: "https://github.com/ga4gh/vmc"
    email: "vmc-contributors@genomicsandhealth.org"
externalDocs: 
  description: "VMC Home"
  url: "https://github.com/ga4gh/vmc"
basePath: "/0"
schemes:
- "https"
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /alleles/{allele_id}:
    get:
      tags: ["Genetic States"]
      summary: "Get specific Allele by Id"
      description: "Returns the specified Allele"
      operationId: "controller.allele_get"
      produces:
      - "application/json"
      parameters:
      - name: "allele_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GeneticStates"
        "404":
          description: "allele_id does not exist"
  /alleles/:
    get:
      tags: ["Genetic States"]
      operationId: "controller.alleles_get"
      summary: "Browse alleles"
      description: "Returns a paginated set of Alleles for a query, or all Alleles"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GeneticStates"
        "404":
          description: "allele_id doesn't exist"
    post:
      tags: ["Genetic States"]
      description: "Adds a new allele"
      operationId: "controller.alleles_post"
      parameters:
      - name: allele
        in: "body"
        description: "Allele to create"
        required: false
        schema:
          $ref: "#/definitions/Allele"
      responses:
        "204":
          description: "Allele created"
          schema:
            $ref: "#/definitions/Allele"
        "400":
          description: "Your allele smells"
  /locations/:
    get:
      tags: ["Locations"]
      operationId: "controller.locations_get"
      summary: "Browse locations"
      description: "Returns a paginated set of Locations for a query, or all Locations"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Location"
            xml:
              name: "Locations"
              wrapped: true
        "404":
          description: "location_id doesn't exist"
    post:
      tags: ["Locations"]
      description: "Adds a new location"
      operationId: "controller.locations_post"
      parameters:
      - name: location
        in: "body"
        description: "Location to create"
        required: false
        schema:
          $ref: "#/definitions/Location"
      responses:
        "204":
          description: "Location created"
          schema:
            $ref: "#/definitions/Location"
        "400":
          description: "Your location smells"

definitions:
  Completeness:
    type: "string"
    description: Declares the `completeness` of haplotype or genotype definitions.
    enum:
    - "UNKNOWN"
    - "PARTIAL"
    - "COMPLETE"
  Sequence:
    type: "string"
  Id:
    description: Uniquely identifies a specific instance of an object within a document.
    type: "string"
    example: "X0123abcd"
    xml:
      attribute: true
  Identifier:
    description: A <namespace,accession> pair that refers to an object.
    type: "object"
    properties:
      namespace:
        type: "string"
        example: "NCBI"
        description: "authority"
      accession:
        type: "string"
        example: "NM_000551.3"
        description: "unique key within namespace"
    required:
    - "accession"
    - "namespace"
  Interval:
    description: A <start,end> position pair, using interbase coordinates.
    type: "object"
    required:
    - "end"
    - "start"
    properties:
      start:
        type: "integer"
      end:
        type: "integer"
    example:
      start: 5
      end: 5
  Location:
    description: An Interval on a Sequence.
    type: "object"
    required:
    - "interval"
    - "sequence_id"
    properties:
      id:
        $ref: "#/definitions/Id"
      sequence_id:
        $ref: "#/definitions/Id"
      interval:
        $ref: "#/definitions/Interval"
    example:
      id: "L001a"
      sequence_id: "S01ab"
      interval:
        start: 22
        end: 23
  Allele:
    description: A contiguous change at a Location.
    type: "object"
    properties:
      id:
        $ref: "#/definitions/Id"
        readOnly: true
      location_id:
        $ref: "#/definitions/Id"
      replacement:
        $ref: "#/definitions/Sequence"
    example:
      id: "A03bc"
      location_id: "L001a"
      replacement: "A"
    xml:
      name: "Allele"
  Haplotype:
    description: A set of zero or more Alleles on a single instance of a Sequence.
    type: "object"
    properties:
      id:
        $ref: "#/definitions/Id"
      completness:
        $ref: "#/definitions/Completeness"
      allele_ids:
        type: "array"
        items:
          $ref: "#/definitions/Id"
    example:
      id: "Ha0f9"
      completeness: "PARTIAL"
      allele_ids: ["A0123", "A0124"]
  Genotype:
    description: A list of Haplotypes.
    type: "object"
    properties:
      id:
        $ref: "#/definitions/Id"
      completness:
        $ref: "#/definitions/Completeness"
      haplotype_ids:
        type: "array"
        items:
          $ref: "#/definitions/Id"
    example:
      id: "G310a"
      completeness: "COMPLETE"
      haplotype_ids: ["H1220", "H19f4"]
  DateTime:
    type: "string"
    format: "date-time"
  Meta:
    type: "object"
    properties:
      version:
        type: "string"
        default: "0"
      date:
        $ref: "#/definitions/DateTime"
  IdIdentifiersMap:
    description: A map of <Id, Identifiers[]>.
    type: "object"
    additionalProperties:
      type: "array"
      items:
        $ref: "#/definitions/Identifier"
    example:
      "S491f":
      - namespace: NCBI
        accession: NM_000551.2
      - namespace: ENST
        accession: BLAHBLAH
      "H19f4":
      - namespace: 
        accession: APOE:ε1
      "H1220":
      - namespace: 
        accession: APOE:ε2
  GeneticStates:
    title: GeneticStates
    description: A collection of Location, Allele, Haplotype, Genotype, and IdIdentiferMap records.
    type: "object"
    properties:
      meta:
        $ref: "#/definitions/Meta"
      locations:
        type: "array"
        items:
          $ref: "#/definitions/Location"
      alleles:
        type: "array"
        items:
          $ref: "#/definitions/Allele"
      haplotypes:
        type: "array"
        items:
          $ref: "#/definitions/Haplotype"
      genotypes:
        type: "array"
        items:
          $ref: "#/definitions/Genotype"
      ididentifers:
        $ref: "#/definitions/IdIdentifiersMap"
