swagger: "2.0"

info:
  title: "Variation Modelling Collaboration"
  description: |
    Standardized exchange of biological sequence variation
    This file may be referenced directly in clients and servers as
    (URL TBD)
  version: "0.0"
  contact:
    name: "Variation Modelling Collaboration"
    url: "https://github.com/ga4gh/vmc"
    email: "vmc-contributors@genomicsandhealth.org"

externalDocs: 
  description: "VMC Home"
  url: "https://github.com/ga4gh/vmc"

basePath: "/0"

schemes:
- "https"
- "http"

consumes:
- "application/json"

produces:
- "application/json"

paths:
  /alleles/{allele_id}:
    get:
      tags: ["Alleles"]
      summary: "Get specific Allele by Id"
      description: "Returns the specified Allele"
      produces:
      - "application/json"
      parameters:
      - name: "allele_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/VMCBundle"
        "404":
          description: "allele_id does not exist"
  /alleles/:
    get:
      tags: ["Alleles"]
      summary: "Browse alleles"
      description: "Returns a paginated set of Alleles for a query, or all Alleles"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/VMCBundle"
        "404":
          description: "allele_id doesn't exist"
    post:
      tags: ["Alleles"]
      description: "Adds a new allele"
      parameters:
      - name: allele
        in: "body"
        description: "Allele to create"
        required: false
        schema:
          $ref: "#/definitions/Allele"
      responses:
        "204":
          description: "Allele created"
          schema:
            $ref: "#/definitions/Allele"
        "400":
          description: "Your allele smells"

  /locations/:
    get:
      tags: ["Locations"]
      summary: "Browse locations"
      description: "Returns a paginated set of Locations for a query, or all Locations"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Location"
            xml:
              name: "Locations"
              wrapped: true
        "404":
          description: "location_id doesn't exist"
    post:
      tags: ["Locations"]
      description: "Adds a new location"
      parameters:
      - name: location
        in: "body"
        description: "Location to create"
        required: false
        schema:
          $ref: "#/definitions/Location"
      responses:
        "204":
          description: "Location created"
          schema:
            $ref: "#/definitions/Location"
        "400":
          description: "Your location smells"

  /vmcbundle/:
    get:
      tags: ["VMCBundle"]
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/VMCBundle"


definitions:
  # Basic types
  DateTime:
    type: "string"
    format: "date-time"

  Id:
    description: Uniquely identifies a specific instance of an object within a document.
    type: "string"
    example: "X0123abcd"
    xml:
      attribute: true

  Identifier:
    description: A <namespace,accession> pair that refers to an object.
    type: "object"
    properties:
      namespace:
        type: "string"
        example: "NCBI"
        description: "authority"
      accession:
        type: "string"
        example: "NM_000551.3"
        description: "unique key within namespace"
    required:
    - "accession"
    - "namespace"

  Meta:
    type: "object"
    properties:
      version:
        type: "string"
        default: "0"
      generated_at:
        $ref: "#/definitions/DateTime"

  # Sequence, Positions, Locations
  Sequence:
    type: "string"

  Interval:
    description: A <start,end> position pair, using interbase coordinates.
    type: "object"
    properties:
      start:
        type: "integer"
      end:
        type: "integer"
    example:
      start: 42
      end: 42
    required:
    - "end"
    - "start"

  Location:
    description: An Interval on a Sequence.
    type: "object"
    properties:
      id:
        $ref: "#/definitions/Id"
      sequence_id:
        $ref: "#/definitions/Id"
      position:
        $ref: "#/definitions/Position"
    required:
    - "position"
    - "sequence_id"
    example:
      id: "VMC:GL01234"
      sequence_id: "VMC:GS01234"
      interval:
        start: 22
        end: 23

  Position:
    type: "object"
    properties:
      type:
        $ref: "#/definitions/PositionType"
      value:
        type: "object"
    required:
    - type
    - value
    example:
      type: "INTERVAL"
      value:
        start: 42
        end: 42

  PositionType:
    type: "string"
    description: Type of position or coordinate within a sequence
    enum:
    - "INTERVAL"
    # later possibilities:
    # - "BASEOFFSET"   # As in hgvs c.
    # - "FUZZY"        # e.g., left-of, right-of, +/-, etc; Consider FALDO
    # - "EXON"         # whole exon ranges (e.g., exons 3-5) (need intronic?)
    # - "BAND"         # e.g., 11q22.12

  # Genetic States
  Allele:
    description: A contiguous change at a Location.
    type: "object"
    properties:
      id:
        $ref: "#/definitions/Id"
      location_id:
        $ref: "#/definitions/Id"
      type:
        $ref: "#/definitions/AlleleType"
      state:
        type: "object"
    example:
      id: "A03bc"
      location_id: "VMC:GL_01234"
      type: "SEQUENCE"
      state:
        sequence: "A"
    xml:
      name: "Allele"

  AlleleType:
    type: "string"
    enum:
    - "SEQUENCE"
    # later:
    # - "CNV"

  AlleleSequence:
    type: "object"
    properties:
      sequence:
        type: "string"
    required:
    - "sequence"

  Completeness:
    type: "string"
    description: Declares the `completeness` of haplotype or genotype definitions.
    enum:
    - "UNKNOWN"
    - "PARTIAL"
    - "COMPLETE"

  Haplotype:
    description: A set of zero or more Alleles on a single instance of a Sequence.
    type: "object"
    properties:
      id:
        $ref: "#/definitions/Id"
      completness:
        $ref: "#/definitions/Completeness"
      allele_ids:
        type: "array"
        items:
          $ref: "#/definitions/Id"
    example:
      completeness: "PARTIAL"
      allele_ids: ["A0123", "A0124"]

  Genotype:
    description: A list of Haplotypes.
    type: "object"
    properties:
      id:
        $ref: "#/definitions/Id"
      completness:
        $ref: "#/definitions/Completeness"
      haplotype_ids:
        type: "array"
        items:
          $ref: "#/definitions/Id"
    example:
      id: "G310a"
      completeness: "COMPLETE"
      haplotype_ids: ["H1220", "H19f4"]

  VMCBundle:
    title: VMCBundle
    description: |
      A complete and consistent collection of Location, Allele,
      Haplotype, Genotype, and IdIdentiferMap records.
    type: "object"
    properties:
      meta:
        $ref: "#/definitions/Meta"
      locations:
        type: "array"
        items:
          $ref: "#/definitions/Location"
      alleles:
        type: "array"
        items:
          $ref: "#/definitions/Allele"
      haplotypes:
        type: "array"
        items:
          $ref: "#/definitions/Haplotype"
      genotypes:
        type: "array"
        items:
          $ref: "#/definitions/Genotype"
      ididentifiers:
        $ref: "#/definitions/IdIdentifiersMap"
    required:
    - meta
    - locations
    - alleles
    - haplotypes
    - genotypes
    - ididentifiers

  # Naming
  IdIdentifiersMap:
    description: "A map of <Id, Identifiers[]>."
    type: "object"
    additionalProperties:
      type: "array"
      items:
        $ref: "#/definitions/Identifier"
    example:
      "S491f":
      - namespace: NCBI
        accession: NM_000551.2
      - namespace: ENST
        accession: BLAHBLAH
      "H19f4":
      - namespace: whoknows
        accession: APOE-ε1
      "H1220":
      - namespace: whoknows
        accession: APOE-ε2
